config/routes.rb
Hatch::Application.routes.draw do
  get "hatch/index"

  resources :weeks
  post 'hatch/redirect_to_show' => 'hatch#redirect_to_show', :as => :redir_to_show
  get 'about' => 'hatch#about', :as => :about
  get 'set_layout' => 'hatch#set_layout'

  root :to => 'hatch#index'

end

app/models/week.rb
class Week < ActiveRecord::Base
  attr_accessible :ending, :starting, :week_number

  def self.current_week
    current = self.where("starting <= ? and ending >= ?", Date.today, Date.today)
    if(current.empty?)
      return 1
    else
      current.first[:week_number]
    end
  end
end

app/models/working_set.rb
class WorkingSet
  attr_reader :reps, :weight, :percentage
  def initialize(work_set, one_repmax)
    @reps = work_set.reps
    if(work_set.reps.nil? or work_set.percentage.nil? or one_repmax.nil?)
      #shouldn't ever happen
      @percentage = @weight = 0
    end
    @percentage = 100 * work_set.percentage
    @weight = work_set.percentage * one_repmax
  end
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  attr_accessible :day, :lift, :percentage, :reps, :week, :set_number

  scope :first_day, where(:day => 1)
  scope :second_day, where(:day => 2)
  scope :by_week, lambda {|week| where(:week => week) unless week.nil?}
  scope :sorted, order(:day, :set_number)
  scope :back_squat, where(:lift => :back_squat)
  scope :front_squat, where(:lift => :front_squat)
  scope :days, select(:day).uniq
  scope :work, select([:reps, :percentage])

end

app/models/workout_generator.rb
class WorkoutGenerator
  attr_reader :work_days, :work_week

  def initialize(week, bs_1rm, fs_1rm)
    bs_1rm > 0.0 or (bs_1rm = 100.0)
    fs_1rm > 0.0 or (fs_1rm = 100.0)

    if(week > 12 and week < 1)
      week = Week.current_week
    end
    @work_week = week
    @bs_1rm = bs_1rm
    @fs_1rm = fs_1rm
    @bs = Workout.by_week(week).back_squat.work.sorted.readonly
    @fs = Workout.by_week(week).front_squat.work.sorted.readonly
  end

  def build(days=%w{1 2})
    @workout = {}
    @work_days = days
    days.each do |day|
      bs_day = @bs.where(:day => day.to_i).map {|set| self.back_squat_set(set)}
      fs_day = @fs.where(:day => day.to_i).map {|set| self.front_squat_set(set)}
      @workout[day] = {:front => fs_day, :back => bs_day}
    end
    self
  end

  def combined
    workout = {}
    @work_days.each do |day|
       workout[day] = @workout[day][:back].zip @workout[day][:front]
    end
    workout
  end

  def flat
    @workout
  end

  def back_squat_set(set)
    WorkingSet.new(set, @bs_1rm);
  end
  def front_squat_set(set)
    WorkingSet.new(set, @fs_1rm);
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout :detect_layout

  protected
  def check_for_mobile
    session[:mobile_override] = params[:mobile] if params[:mobile]
    prepare_for_mobile if mobile_device?
  end

  def prepare_for_mobile
    prepend_view_path Rails.root + 'app' + 'views_mobile'
  end

  def detect_layout
    mobile_device? ? 'mobile_application' : 'application'
  end

  def mobile_device?
    if session[:mobile_override]
      session[:mobile_override] == "1"
    else
      # Season this regexp to taste. I prefer to treat iPad as non-mobile.
      (request.user_agent =~ /(iPhone|iPod|Android|webOS|Mobile)/) && (request.user_agent !~ /iPad/)
    end
  end
  helper_method :mobile_device?
end
  

app/controllers/hatch_controller.rb
class HatchController < ApplicationController
  before_filter :check_for_mobile, :only => [:index]
  def index
    @current_week = Week.current_week
    @keep = session[:keep] ||= cookies[:keep]

    @bs ||= session[:bs_1rm] ||= cookies[:bs_1rm] 
    @fs ||= session[:fs_1rm] ||= cookies[:fs_1rm]

    @bs  ||= 100.0
    @fs  ||= 100.0

    @default_days = (mobile_device? ? 'Day 1' : 'Both')
  end

  def about
    @smiley="\u{1F60E}"
  end

  def redirect_to_show
    keep = session[:keep] = params[:keep]
    bs_1rm = params[:backsquat_1rm]
    fs_1rm = params[:frontsquat_1rm]
    days = case params[:days]
    when 'Day 1'
      1
    when 'Day 2'
      2
#when 'Both'
    else
      0
    end
#session[:week]=params[:week]
    session[:bs_1rm]=bs_1rm
    session[:fs_1rm]=fs_1rm
    if keep
      cookies[:bs_1rm]=bs_1rm
      cookies[:fs_1rm]=fs_1rm
    end
    redirect_to week_path(:id => params[:week], 
      :bs_1rm => bs_1rm , :fs_1rm => fs_1rm, :days => days)
  end

  def set_layout
    override = params[:mobile]
    if(override.nil? or override.empty? or override == 'auto')
      session.delete(:mobile_override)
    else
      session[:mobile_override] = params[:mobile]
    end
    redirect_to root_path
  end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_filter :check_for_mobile
  def show
    week = (params[:id]).to_i
    bs_1rm = params[:bs_1rm].to_f 
    fs_1rm = params[:fs_1rm].to_f 
    days = params[:days]
    days = case days.to_i
    when 1
      %w{1}
    when 2
      %w{2}
    else
      %w{1 2}
    end
    @workout = WorkoutGenerator.new(week, bs_1rm, fs_1rm)
    @workout.build(days)
    @days = @workout.work_days
    @week = @workout.work_week
    @lifts = {
      :back => 'Back Squat',
      :front => 'Front Squat'
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hatch_helper.rb
module HatchHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/hatch/about.html.haml
%h1 About
%p In July of 2014, CrossFit Mission Gorge started programming some workouts based on having athletes follow Gayle Hatch's lifting program.
%p This little web page is up to make it easier for athletes to figure out their lifts for a given day in any week of the program.  It is offered free as a service to CFMG's members and the CrossFit community at large.
%p NOTE: if you don't know your one-rep max for front and back squat I'd say that you don't need this calculator, you need a coach.
=link_to 'About the Hatch Squat Program', 'http://www.mikesgym.org/programs/index.php?show=program&programID=19'
%br
=link_to 'About CrossFit Mission Gorge', 'http://www.crossfitmissiongorge.com/'
="(the best gym in SoCal)"
=image_tag 'http://www.neophi.com/home/aris/smiley_1.png'
%p Bias aside, the combination of great coaching, solid well-thought-out programming, and an amazing community have made this place a home-away-from-home for so many of us.  If you're in SD, drop by, say "Hi!" and throw down a WOD with us...

%h3 Some geeky info about this site
%p This site was written as a Rails app, which some would say is overkill for a page that could essentially be written as a single PHP sheet.  It is meant to be transparently mobile-adaptive.  I'm just wrapping up a Software as a Service class and this seemed like a good little exercise as well as a convenience for our community.  If you give the page nonsense inputs it will just simply default in the current week at CFMG (or 1 once the program is over) and assume your one rep max is 100 pounds.
%br
%p Keep on squattin'
%p   -Ari
=link_to 'Back to the Calculator', hatch_index_path

app/views/hatch/index.html.haml
%h1 CFMG Hatch Program Calculator
= form_tag redir_to_show_path do
  Week: 
  = select_tag :week, options_for_select(('1'..'12').to_a.zip(1..12).to_a, @current_week)
  %br
  Back Squat 1rm: 
  = text_field_tag 'backsquat_1rm', @bs, :size => 4
  %br
  Front Squat 1rm: 
  = text_field_tag 'frontsquat_1rm', @fs, :size => 4
  %br
  - [ 'Day 1', 'Day 2', 'Both'].each do |days|
    %label
      = radio_button_tag :days, days, days == @default_days
      = days.humanize
  = submit_tag 'Calculate'
  = check_box_tag 'keep', 1, @keep
  = 'Save for next time'
%br
=link_to 'About', about_path
%p.small 
  [
  =link_to 'Mobile', :action => "set_layout", :mobile => "1" 
  |
  =link_to 'Full', :action => "set_layout", :mobile => "0" 
  |
  =link_to 'Auto', :action => "set_layout", :mobile => 'auto'
  ]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hatch</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/mobile_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hatch</title>
  <meta name=viewport content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag  "mobile_application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/weeks/show.html.haml
%h1= "Week #{@week}"
-@days.each do |day| 
  %h2= "Day #{day}"
  %table.workout{:id => "day_#{day}"}
    %thead
      %tr
        %th.lift{:colspan => 3} Back Squat 
        %th.lift{:colspan => 3} Front Squat 
      %tr
        %th.scheme Reps
        %th.scheme %1RM
        %th.scheme Weight 
        %th.scheme Reps
        %th.scheme %1RM
        %th.scheme Weight 
    %tbody
      -@workout.combined()[day].each do |set| 
        %tr
          %td.entry= set.first.reps
          %td.entry= set.first.percentage 
          %td.entry= set.first.weight.round(2)
          -if set.last.nil? 
            %td/
            %td/
            %td/
          -else
            %td.entry= set.last.reps
            %td.entry= set.last.percentage 
            %td.entry= set.last.weight.round(2)
          